export enum PlatformRole {
  FARMER = 'FARMER',
  PROMOTER = 'PROMOTER',
  SALES_PARTNER = 'SALES_PARTNER',
  DISTRIBUTOR_OWNER = 'DISTRIBUTOR_OWNER',
  DISTRIBUTOR_STAFF = 'DISTRIBUTOR_STAFF',
  COMPANY_OWNER = 'COMPANY_OWNER',
  COMPANY_STAFF = 'COMPANY_STAFF',
  SERVICE_PROVIDER = 'SERVICE_PROVIDER',
  DELIVERY_PARTNER = 'DELIVERY_PARTNER',
  SUPPORT_AGENT = 'SUPPORT_AGENT',
  OPERATIONS_MANAGER = 'OPERATIONS_MANAGER',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  CATALOGUE_REVIEWER = 'CATALOGUE_REVIEWER',
  AGRONOMIST = 'AGRONOMIST',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum OrganisationType {
  VARDHNAM = 'VARDHNAM',
  COMPANY = 'COMPANY',
  DISTRIBUTOR = 'DISTRIBUTOR',
  SERVICE_PROVIDER = 'SERVICE_PROVIDER',
}

export enum MembershipStatus {
  INVITED = 'INVITED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REMOVED = 'REMOVED',
}

export enum CartStatus {
  ACTIVE = 'ACTIVE',
  ABANDONED = 'ABANDONED',
}

export enum OrderType {
  PRODUCT_ORDER = 'PRODUCT_ORDER',
  SERVICE_ORDER = 'SERVICE_ORDER',
}

export enum ProductCheckoutStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAYMENT_PROCESSING = 'PAYMENT_PROCESSING',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
}

export enum ProductOrderStatus {
  DRAFT = 'DRAFT',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAYMENT_PROCESSING = 'PAYMENT_PROCESSING',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  CONFIRMED = 'CONFIRMED',
  DISTRIBUTOR_ACCEPTED = 'DISTRIBUTOR_ACCEPTED',
  DISTRIBUTOR_REJECTED = 'DISTRIBUTOR_REJECTED',
  INVENTORY_RESERVED = 'INVENTORY_RESERVED',
  READY_TO_PACK = 'READY_TO_PACK',
  PACKED = 'PACKED',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
  CANCELLATION_REQUESTED = 'CANCELLATION_REQUESTED',
  CANCELLED = 'CANCELLED',
  RETURN_REQUESTED = 'RETURN_REQUESTED',
  RETURN_APPROVED = 'RETURN_APPROVED',
  RETURN_REJECTED = 'RETURN_REJECTED',
  RETURN_IN_TRANSIT = 'RETURN_IN_TRANSIT',
  RETURNED = 'RETURNED',
  REFUND_PENDING = 'REFUND_PENDING',
  REFUNDED = 'REFUNDED',
  DISPUTED = 'DISPUTED',
  CLOSED = 'CLOSED',
}

export enum ProductInvoiceStatus {
  GENERATED = 'GENERATED',
  VOIDED = 'VOIDED',
}

export enum ProductDispatchStatus {
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  CANCELLED = 'CANCELLED',
}

export enum ProductDeliveryAssignmentStatus {
  ASSIGNED = 'ASSIGNED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
  CANCELLED = 'CANCELLED',
}

export enum ReturnPickupAssignmentStatus {
  ASSIGNED = 'ASSIGNED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  COLLECTED = 'COLLECTED',
  CANCELLED = 'CANCELLED',
}

export enum DeliveryFailureReasonCode {
  FARMER_UNAVAILABLE = 'FARMER_UNAVAILABLE',
  FARMER_REFUSED = 'FARMER_REFUSED',
  ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
  ACCESS_RESTRICTED = 'ACCESS_RESTRICTED',
  VEHICLE_BREAKDOWN = 'VEHICLE_BREAKDOWN',
  WEATHER_OR_ROUTE_BLOCKED = 'WEATHER_OR_ROUTE_BLOCKED',
  PACKAGE_DAMAGED = 'PACKAGE_DAMAGED',
  OTHER = 'OTHER',
}

export enum PaymentProviderMode {
  MOCK = 'MOCK',
}

export enum PaymentIntentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
}

export enum PaymentEventType {
  INTENT_CREATED = 'INTENT_CREATED',
  CONFIRMATION_STARTED = 'CONFIRMATION_STARTED',
  PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
}

export interface ApiErrorEnvelope {
  error: {
    code: string;
    message: string;
    statusCode: number;
    requestId: string;
    timestamp: string;
    details?: unknown;
  };
}

export interface ApiSuccessEnvelope<TData> {
  data: TData;
  requestId: string;
}
