import { randomUUID } from 'node:crypto';
import {
  BadRequestException,
  ConflictException,
  ForbiddenException,
  Inject,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { StoredFile, StoredFilePurpose, StoredFileStatus } from '@prisma/client';
import { AccessService } from '../access/access.service';
import { PermissionCode } from '../access/permission-codes';
import { AuditService } from '../audit/audit.service';
import type { CurrentUser } from '../auth/current-user.interface';
import { withAuditActor } from '../common/audit-actor';
import { ApiErrorCode } from '../common/errors/api-error-codes';
import { QueueService } from '../jobs/queue.service';
import { DocumentJob, QueueName } from '../jobs/queue-names';
import { PrismaService } from '../prisma/prisma.service';
import type { ConfirmUploadDto } from './dto/confirm-upload.dto';
import type { RequestUploadUrlDto } from './dto/request-upload-url.dto';
import { STORAGE_PROVIDER, type StorageProvider } from './storage.provider.interface';
import { isClientUploadablePurpose, normaliseContentType, uploadPolicyFor } from './upload-policy';

@Injectable()
export class FilesService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly auditService: AuditService,
    private readonly accessService: AccessService,
    private readonly configService: ConfigService,
    private readonly queueService: QueueService,
    @Inject(STORAGE_PROVIDER) private readonly storage: StorageProvider,
  ) {}

  async requestUploadUrl(dto: RequestUploadUrlDto, actor: CurrentUser, requestId?: string) {
    if (!isClientUploadablePurpose(dto.purpose)) {
      throw new ForbiddenException({
        code: ApiErrorCode.FORBIDDEN,
        message: `${dto.purpose} files are generated by the platform and cannot be uploaded`,
      });
    }

    const policy = uploadPolicyFor(dto.purpose);
    const contentType = normaliseContentType(dto.contentType);

    if (!policy.allowedContentTypes.includes(contentType)) {
      throw new BadRequestException({
        code: ApiErrorCode.VALIDATION_FAILED,
        message: `${contentType} is not permitted for ${dto.purpose}`,
        details: { allowedContentTypes: policy.allowedContentTypes },
      });
    }

    if (dto.sizeBytes > policy.maxSizeBytes) {
      throw new BadRequestException({
        code: ApiErrorCode.VALIDATION_FAILED,
        message: `${dto.purpose} files may not exceed ${policy.maxSizeBytes} bytes`,
        details: { maxSizeBytes: policy.maxSizeBytes },
      });
    }

    const expiresInSeconds = this.uploadUrlTtlSeconds();
    const objectKey = this.buildObjectKey(dto.purpose, dto.filename);
    const target = await this.storage.getUploadUrl(objectKey, contentType, expiresInSeconds);

    const storedFile = await this.prisma.$transaction(async (tx) => {
      const created = await tx.storedFile.create({
        data: {
          ownerUserId: actor.userId,
          organisationId: actor.organisationId,
          purpose: dto.purpose,
          status: StoredFileStatus.PENDING_UPLOAD,
          objectKey,
          originalFilename: dto.filename,
          contentType,
          declaredSizeBytes: dto.sizeBytes,
          uploadUrlExpiresAt: target.expiresAt,
        },
      });

      await this.auditService.record(
        withAuditActor(actor, {
          action: 'STORED_FILE_UPLOAD_REQUESTED',
          resourceType: 'StoredFile',
          resourceId: created.id,
          newValue: {
            purpose: created.purpose,
            contentType: created.contentType,
            declaredSizeBytes: created.declaredSizeBytes,
          },
          ...(requestId ? { requestId } : {}),
        }),
        tx,
      );

      return created;
    });

    return {
      fileId: storedFile.id,
      uploadUrl: target.url,
      requiredHeaders: target.requiredHeaders,
      expiresAt: target.expiresAt.toISOString(),
      maxSizeBytes: policy.maxSizeBytes,
    };
  }

  /**
   * Confirms that bytes actually landed, and re-validates them.
   *
   * The presigned URL is a capability to write anything, so what the client
   * declared at issue time proves nothing. Size and content type are checked
   * again here against the object the storage provider actually holds.
   */
  async confirmUpload(
    fileId: string,
    dto: ConfirmUploadDto,
    actor: CurrentUser,
    requestId?: string,
  ) {
    const file = await this.getOwnedPendingFile(fileId, actor);
    const policy = uploadPolicyFor(file.purpose);
    const metadata = await this.storage.getMetadata(file.objectKey);

    if (!metadata) {
      throw new BadRequestException({
        code: ApiErrorCode.VALIDATION_FAILED,
        message: 'No uploaded object was found for this file',
      });
    }

    const observedContentType = normaliseContentType(metadata.contentType);
    const rejection = this.rejectionReasonFor(policy, metadata.sizeBytes, observedContentType);

    if (rejection) {
      await this.rejectFile(file, rejection, actor, requestId);
      throw new BadRequestException({
        code: ApiErrorCode.VALIDATION_FAILED,
        message: rejection,
      });
    }

    if (dto.checksumSha256 && metadata.checksumSha256 !== dto.checksumSha256) {
      await this.rejectFile(file, 'Checksum did not match the uploaded object', actor, requestId);
      throw new BadRequestException({
        code: ApiErrorCode.VALIDATION_FAILED,
        message: 'Checksum did not match the uploaded object',
      });
    }

    const updated = await this.prisma.$transaction(async (tx) => {
      const next = await tx.storedFile.update({
        where: { id: file.id },
        data: {
          status: StoredFileStatus.PENDING_SCAN,
          sizeBytes: metadata.sizeBytes,
          ...(metadata.checksumSha256 ? { checksumSha256: metadata.checksumSha256 } : {}),
          contentType: observedContentType,
          uploadedAt: new Date(),
        },
      });

      await this.auditService.record(
        withAuditActor(actor, {
          action: 'STORED_FILE_UPLOAD_CONFIRMED',
          resourceType: 'StoredFile',
          resourceId: next.id,
          previousValue: { status: file.status },
          newValue: {
            status: next.status,
            sizeBytes: next.sizeBytes,
            contentType: next.contentType,
          },
          ...(requestId ? { requestId } : {}),
        }),
        tx,
      );

      return next;
    });

    // Enqueued after the transaction commits, so a rolled-back confirm never
    // leaves a scan job pointing at a file that was not accepted.
    await this.queueService.enqueue(
      QueueName.DOCUMENTS,
      DocumentJob.SCAN_STORED_FILE,
      { storedFileId: updated.id },
      // A stable id makes a duplicated confirm enqueue one scan, not two.
      // The separator is a hyphen: BullMQ rejects a colon in a custom job id,
      // the same constraint that applies to queue names.
      { ...(requestId ? { requestId } : {}), jobId: `scan-${updated.id}` },
    );

    return this.present(updated);
  }

  async getFile(fileId: string, actor: CurrentUser) {
    const file = await this.findFileOrThrow(fileId);
    this.assertCanRead(file, actor);
    return this.present(file);
  }

  /**
   * Issues a short-lived download URL. Downloads are authorised here, in the
   * API -- the bucket is never public -- and PII-bearing purposes are audited.
   */
  async getDownloadUrl(fileId: string, actor: CurrentUser, requestId?: string) {
    const file = await this.findFileOrThrow(fileId);
    this.assertCanRead(file, actor);

    if (file.status !== StoredFileStatus.AVAILABLE) {
      throw new ConflictException({
        code: ApiErrorCode.CONFLICT,
        message: `File is not available for download (status ${file.status})`,
      });
    }

    const target = await this.storage.getDownloadUrl(file.objectKey, this.downloadUrlTtlSeconds());

    if (uploadPolicyFor(file.purpose).auditDownloads) {
      await this.auditService.record(
        withAuditActor(actor, {
          action: 'STORED_FILE_DOWNLOADED',
          resourceType: 'StoredFile',
          resourceId: file.id,
          ...(file.organisationId ? { organisationId: file.organisationId } : {}),
          newValue: { purpose: file.purpose },
          ...(requestId ? { requestId } : {}),
        }),
      );
    }

    return { downloadUrl: target.url, expiresAt: target.expiresAt.toISOString() };
  }

  /**
   * Loads a file for the scan job. Returns undefined when it is no longer
   * awaiting a scan, so a replayed job exits quietly instead of re-scanning.
   */
  async getFileForScan(storedFileId: string): Promise<StoredFile | undefined> {
    const file = await this.prisma.storedFile.findUnique({ where: { id: storedFileId } });
    return file?.status === StoredFileStatus.PENDING_SCAN ? file : undefined;
  }

  /** Called by the scan job once a verdict exists. */
  async applyScanResult(
    storedFileId: string,
    result: 'CLEAN' | 'INFECTED' | 'SCAN_FAILED',
    requestId?: string,
  ) {
    const file = await this.findFileOrThrow(storedFileId);

    if (file.status !== StoredFileStatus.PENDING_SCAN) {
      // Scans are idempotent: a replayed job must not resurrect a rejected file
      // or re-clear one an operator has since acted on.
      return this.present(file);
    }

    const status =
      result === 'CLEAN'
        ? StoredFileStatus.AVAILABLE
        : result === 'INFECTED'
          ? StoredFileStatus.INFECTED
          : StoredFileStatus.PENDING_SCAN;

    // A failed scan is not a verdict. Leave the file unscanned and let the job
    // retry rather than marking it clean or condemning it.
    if (result === 'SCAN_FAILED') {
      throw new Error(`Virus scan failed for stored file ${storedFileId}`);
    }

    const updated = await this.prisma.$transaction(async (tx) => {
      const next = await tx.storedFile.update({
        where: { id: file.id },
        data: {
          status,
          scanResult: result,
          scanCompletedAt: new Date(),
          ...(result === 'INFECTED' ? { rejectionReason: 'Malware detected during scan' } : {}),
        },
      });

      await this.auditService.record(
        withAuditActor(
          { kind: 'system', source: `job:${DocumentJob.SCAN_STORED_FILE}` },
          {
            action: result === 'CLEAN' ? 'STORED_FILE_SCAN_CLEARED' : 'STORED_FILE_SCAN_REJECTED',
            resourceType: 'StoredFile',
            resourceId: next.id,
            ...(next.organisationId ? { organisationId: next.organisationId } : {}),
            previousValue: { status: file.status },
            newValue: { status: next.status, scanResult: next.scanResult },
            ...(requestId ? { requestId } : {}),
          },
        ),
        tx,
      );

      return next;
    });

    return this.present(updated);
  }

  private async rejectFile(
    file: StoredFile,
    reason: string,
    actor: CurrentUser,
    requestId?: string,
  ): Promise<void> {
    await this.prisma.$transaction(async (tx) => {
      await tx.storedFile.update({
        where: { id: file.id },
        data: { status: StoredFileStatus.REJECTED, rejectionReason: reason },
      });

      await this.auditService.record(
        withAuditActor(actor, {
          action: 'STORED_FILE_REJECTED',
          resourceType: 'StoredFile',
          resourceId: file.id,
          previousValue: { status: file.status },
          newValue: { status: StoredFileStatus.REJECTED },
          reason,
          ...(requestId ? { requestId } : {}),
        }),
        tx,
      );
    });

    // The bytes failed validation, so there is no reason to retain them.
    await this.storage.delete(file.objectKey).catch(() => undefined);
  }

  private rejectionReasonFor(
    policy: ReturnType<typeof uploadPolicyFor>,
    sizeBytes: number,
    contentType: string,
  ): string | undefined {
    if (sizeBytes > policy.maxSizeBytes) {
      return `Uploaded object exceeds the maximum permitted size of ${policy.maxSizeBytes} bytes`;
    }
    if (!policy.allowedContentTypes.includes(contentType)) {
      return `Uploaded object content type ${contentType} is not permitted for this purpose`;
    }
    return undefined;
  }

  private async getOwnedPendingFile(fileId: string, actor: CurrentUser): Promise<StoredFile> {
    const file = await this.findFileOrThrow(fileId);

    // Only the uploader may complete their own upload, regardless of any
    // administrative read permission.
    if (file.ownerUserId !== actor.userId) {
      throw new ForbiddenException({
        code: ApiErrorCode.FORBIDDEN,
        message: 'Only the uploader can confirm this upload',
      });
    }

    if (file.status !== StoredFileStatus.PENDING_UPLOAD) {
      throw new ConflictException({
        code: ApiErrorCode.CONFLICT,
        message: `Upload has already been processed (status ${file.status})`,
      });
    }

    if (file.uploadUrlExpiresAt.getTime() < Date.now()) {
      throw new ConflictException({
        code: ApiErrorCode.CONFLICT,
        message: 'Upload URL has expired; request a new one',
      });
    }

    return file;
  }

  private async findFileOrThrow(fileId: string): Promise<StoredFile> {
    const file = await this.prisma.storedFile.findUnique({ where: { id: fileId } });
    if (!file) {
      throw new NotFoundException({
        code: ApiErrorCode.NOT_FOUND,
        message: 'File not found',
      });
    }
    return file;
  }

  /**
   * Read access, most permissive first:
   * - anyone holding `files:read:any` (operations and administrators);
   * - the uploader;
   * - a member of the organisation the file belongs to, holding `files:read:own`.
   *
   * A file with no organisation (a farmer's own evidence) is readable only by
   * its owner and by `files:read:any` holders.
   */
  private assertCanRead(file: StoredFile, actor: CurrentUser): void {
    if (this.accessService.hasPermission(actor, PermissionCode.FILES_READ_ANY)) {
      return;
    }

    if (file.ownerUserId === actor.userId) {
      return;
    }

    const sameOrganisation =
      file.organisationId !== null && file.organisationId === actor.organisationId;

    if (
      sameOrganisation &&
      this.accessService.hasPermission(actor, PermissionCode.FILES_READ_OWN)
    ) {
      return;
    }

    throw new ForbiddenException({
      code: ApiErrorCode.FORBIDDEN,
      message: 'You do not have access to this file',
    });
  }

  private present(file: StoredFile) {
    // The object key is never exposed: it is an internal storage address, and
    // publishing it invites clients to construct their own URLs.
    return {
      id: file.id,
      purpose: file.purpose,
      status: file.status,
      originalFilename: file.originalFilename,
      contentType: file.contentType,
      sizeBytes: file.sizeBytes,
      checksumSha256: file.checksumSha256,
      scanResult: file.scanResult,
      rejectionReason: file.rejectionReason,
      uploadedAt: file.uploadedAt?.toISOString() ?? null,
      createdAt: file.createdAt.toISOString(),
    };
  }

  private buildObjectKey(purpose: StoredFilePurpose, filename: string): string {
    const now = new Date();
    const yyyymm = `${now.getUTCFullYear()}${String(now.getUTCMonth() + 1).padStart(2, '0')}`;
    const extension = filename.includes('.')
      ? filename
          .slice(filename.lastIndexOf('.') + 1)
          .toLowerCase()
          .replace(/[^a-z0-9]/g, '')
      : '';
    // The client filename never becomes part of the key: it is untrusted input
    // and would leak personal data into storage paths and access logs.
    return `${purpose.toLowerCase()}/${yyyymm}/${randomUUID()}${extension ? `.${extension}` : ''}`;
  }

  private uploadUrlTtlSeconds(): number {
    return this.configService.get<number>('STORAGE_UPLOAD_URL_TTL_SECONDS') ?? 900;
  }

  private downloadUrlTtlSeconds(): number {
    return this.configService.get<number>('STORAGE_DOWNLOAD_URL_TTL_SECONDS') ?? 300;
  }
}
