/**
 * Object storage behind a provider interface.
 *
 * Bytes never pass through the API. The client asks for an upload URL, writes
 * directly to storage, then confirms; downloads are the same in reverse. That
 * keeps large-file traffic off the request path, which matters more here than
 * usual because the same endpoints are used from rural mobile connections.
 */
export interface StoredObjectMetadata {
  sizeBytes: number;
  contentType: string;
  checksumSha256?: string;
}

export interface UploadTarget {
  /** Absolute URL the client writes bytes to, with `PUT`. */
  url: string;
  expiresAt: Date;
  /** Headers the client must send for the write to be accepted. */
  requiredHeaders: Record<string, string>;
}

export interface DownloadTarget {
  url: string;
  expiresAt: Date;
}

export interface StorageProvider {
  readonly name: string;
  getUploadUrl(
    objectKey: string,
    contentType: string,
    expiresInSeconds: number,
  ): Promise<UploadTarget>;
  getDownloadUrl(objectKey: string, expiresInSeconds: number): Promise<DownloadTarget>;
  getMetadata(objectKey: string): Promise<StoredObjectMetadata | undefined>;
  /** Reads the whole object. Used by the virus scanner, not by request handlers. */
  read(objectKey: string): Promise<Buffer>;
  /** Writes trusted, platform-generated bytes without issuing a client capability. */
  write(objectKey: string, contents: Buffer, contentType: string): Promise<void>;
  delete(objectKey: string): Promise<void>;
}

export const STORAGE_PROVIDER = Symbol('STORAGE_PROVIDER');
