import { StoredFilePurpose } from '@prisma/client';

/**
 * What each kind of file is allowed to be.
 *
 * This is enforced **twice**: when the upload URL is issued, and again when the
 * client confirms. A presigned URL is a capability to write bytes -- the client
 * can put anything at all behind it -- so the declared content type at issue
 * time is a hint, not a guarantee. Only the observed object is authoritative.
 */
export interface UploadPolicy {
  readonly allowedContentTypes: ReadonlyArray<string>;
  readonly maxSizeBytes: number;
  /**
   * Whether every download must be audited. KYC documents contain PII and
   * `AGENTS.md` requires high-risk exports to be logged.
   */
  readonly auditDownloads: boolean;
}

const MB = 1024 * 1024;

const IMAGE_TYPES = ['image/jpeg', 'image/png', 'image/webp'] as const;
const DOCUMENT_TYPES = ['application/pdf', ...IMAGE_TYPES] as const;

const policies: Readonly<Record<StoredFilePurpose, UploadPolicy>> = {
  [StoredFilePurpose.KYC_DOCUMENT]: {
    allowedContentTypes: DOCUMENT_TYPES,
    maxSizeBytes: 10 * MB,
    auditDownloads: true,
  },
  [StoredFilePurpose.PRODUCT_IMAGE]: {
    allowedContentTypes: IMAGE_TYPES,
    maxSizeBytes: 5 * MB,
    auditDownloads: false,
  },
  [StoredFilePurpose.PRODUCT_DOCUMENT]: {
    allowedContentTypes: DOCUMENT_TYPES,
    maxSizeBytes: 10 * MB,
    auditDownloads: false,
  },
  // Captured on a phone in a field, often on a poor connection: keep the ceiling
  // low enough that an upload can actually complete on 2G.
  [StoredFilePurpose.DELIVERY_PROOF]: {
    allowedContentTypes: IMAGE_TYPES,
    maxSizeBytes: 5 * MB,
    auditDownloads: false,
  },
  [StoredFilePurpose.RETURN_EVIDENCE]: {
    allowedContentTypes: IMAGE_TYPES,
    maxSizeBytes: 5 * MB,
    auditDownloads: false,
  },
  [StoredFilePurpose.SUPPORT_EVIDENCE]: {
    allowedContentTypes: DOCUMENT_TYPES,
    maxSizeBytes: 10 * MB,
    auditDownloads: false,
  },
  [StoredFilePurpose.VISIT_EVIDENCE]: {
    allowedContentTypes: IMAGE_TYPES,
    maxSizeBytes: 5 * MB,
    auditDownloads: false,
  },
  // Generated by the platform (WP-15B), never client-uploaded, but it flows
  // through the same storage and download-authorisation path.
  [StoredFilePurpose.INVOICE_PDF]: {
    allowedContentTypes: ['application/pdf'],
    maxSizeBytes: 5 * MB,
    auditDownloads: true,
  },
  [StoredFilePurpose.CREDIT_NOTE_PDF]: {
    allowedContentTypes: ['application/pdf'],
    maxSizeBytes: 5 * MB,
    auditDownloads: true,
  },
  [StoredFilePurpose.SERVICE_EVIDENCE]: {
    allowedContentTypes: IMAGE_TYPES,
    maxSizeBytes: 5 * MB,
    auditDownloads: false,
  },
};

export function uploadPolicyFor(purpose: StoredFilePurpose): UploadPolicy {
  return policies[purpose];
}

/**
 * Financial PDFs are produced by the platform. Accepting client uploads for
 * either purpose would let a participant supply their own financial document.
 */
export function isClientUploadablePurpose(purpose: StoredFilePurpose): boolean {
  return (
    purpose !== StoredFilePurpose.INVOICE_PDF &&
    purpose !== StoredFilePurpose.CREDIT_NOTE_PDF
  );
}

/** Normalises a content type for comparison: `image/jpeg; charset=x` → `image/jpeg`. */
export function normaliseContentType(contentType: string): string {
  return contentType.split(';')[0]!.trim().toLowerCase();
}

export const allowedContentTypesForAllPurposes: ReadonlyArray<string> = [
  ...new Set(Object.values(policies).flatMap((policy) => [...policy.allowedContentTypes])),
];
