name: vardhnam_partner_mobile
description: Partner mobile application for Vardhnam Agrotech.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.12.0 <4.0.0'
  flutter: '>=3.44.9 <3.45.0'

dependencies:
  dio: ^5.11.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.4.1
  flutter_secure_storage: 10.3.1
  go_router: ^17.3.0
  geolocator: ^14.0.2
  intl: ^0.20.2
  mobile_scanner: ^7.1.4
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
