export const portalCopy = {
  title: 'Business Portal',
  phase: 'Marketplace Platform',
  navigationLabel: 'Business portal sections',
  navItems: [
    {
      key: 'dashboard',
      label: 'Dashboard',
      href: '/',
      // Granted to every role -- see permission-codes.ts -- so this is always
      // the first reachable item and `portalLandingPath` lands everyone here.
      anyPermission: ['dashboards:read'],
    },
    {
      key: 'onboarding',
      label: 'Onboarding',
      href: '/onboarding',
      anyPermission: ['onboarding:queue:read'],
    },
    {
      key: 'catalogue',
      label: 'Catalogue',
      href: '/catalogue',
      anyPermission: ['catalogue:read:any', 'catalogue:read:own'],
    },
    {
      key: 'inventory',
      label: 'Inventory',
      href: '/inventory',
      anyPermission: ['inventory:read:any', 'inventory:read:own'],
    },
    {
      key: 'offers',
      label: 'Offers',
      href: '/offers',
      anyPermission: ['offers:read:any', 'offers:read:own'],
    },
    {
      key: 'orders',
      label: 'Orders',
      href: '/orders',
      anyPermission: ['fulfilment-orders:read:any', 'fulfilment-orders:read:own'],
    },
    {
      key: 'returns',
      label: 'Returns',
      href: '/returns',
      anyPermission: ['returns:read:any', 'returns:read:seller-own'],
    },
    {
      key: 'disputes',
      label: 'Disputes',
      href: '/disputes',
      anyPermission: ['disputes:read:any'],
    },
    {
      key: 'advisory',
      label: 'Advisories',
      href: '/advisory',
      anyPermission: ['advisory-rules:manage', 'advisory-rules:review'],
    },
    {
      key: 'kisanClub',
      label: 'Kisan Club',
      href: '/kisan-club',
      anyPermission: ['kisan-club-memberships:read:any'],
    },
    {
      key: 'kisanNetwork',
      label: 'Club Network',
      href: '/kisan-club/network',
      anyPermission: ['kisan-club-territories:manage', 'kisan-club-promoter-profiles:manage'],
    },
    {
      key: 'kisanIntelligence',
      label: 'Club Intelligence',
      href: '/kisan-club/intelligence',
      anyPermission: ['kisan-club-intelligence:read'],
    },
    {
      key: 'finance',
      label: 'Finance',
      href: '/finance',
      anyPermission: [
        'finance-commission-rules:read',
        'finance-ledger:read',
        'finance-commission-entries:read',
        'finance-settlements:read',
      ],
    },
    {
      key: 'payouts',
      label: 'Payouts',
      href: '/payouts/accounts',
      anyPermission: ['payout-accounts:read:any', 'payout-accounts:read:own', 'payout-statements:read:own'],
    },
    {
      key: 'kisanCommercial',
      label: 'Club Commercial',
      href: '/kisan-club/commercial',
      anyPermission: ['kisan-club-programmes:manage', 'kisan-club-benefits:manage'],
    },
    {
      key: 'kisanFulfilment',
      label: 'Club Fulfilment',
      href: '/kisan-club/fulfilment',
      anyPermission: ['kisan-club-fulfilment:read:own', 'kisan-club-fulfilment:read:any'],
    },
    {
      key: 'support',
      label: 'Support',
      href: '/support',
      anyPermission: ['support-tickets:read:any'],
    },
    {
      key: 'notifications',
      label: 'Notifications',
      href: '/notifications',
      anyPermission: ['notifications:read:any'],
    },
    {
      key: 'tally',
      label: 'Tally',
      href: '/tally',
      anyPermission: ['tally-sync:read'],
    },
    {
      key: 'organisations',
      label: 'Organisations',
      href: '/organisations',
      anyPermission: ['organisations:read:any'],
    },
    {
      key: 'users',
      label: 'Users',
      href: '/users',
      anyPermission: ['users:read:any'],
    },
    {
      key: 'jobs',
      label: 'Jobs',
      href: '/admin/jobs',
      anyPermission: ['jobs:read'],
    },
    {
      key: 'audit',
      label: 'Audit',
      href: '/audit',
      anyPermission: ['audit:read'],
    },
  ],
  statusLabel: 'System status',
} as const;
