import { PlatformRole } from '@prisma/client';

export const PermissionCode = {
  USERS_READ_ANY: 'users:read:any',
  USERS_CREATE: 'users:create',
  USERS_UPDATE_ANY: 'users:update:any',
  ORGANISATIONS_READ_ANY: 'organisations:read:any',
  ORGANISATIONS_READ_OWN: 'organisations:read:own',
  ORGANISATIONS_CREATE: 'organisations:create',
  ORGANISATIONS_UPDATE_ANY: 'organisations:update:any',
  ORGANISATIONS_APPROVE: 'organisations:approve',
  MEMBERSHIPS_READ_ANY: 'memberships:read:any',
  MEMBERSHIPS_READ_OWN: 'memberships:read:own',
  MEMBERSHIPS_CREATE: 'memberships:create',
  MEMBERSHIPS_UPDATE_ANY: 'memberships:update:any',
  ONBOARDING_READ_ANY: 'onboarding:read:any',
  ONBOARDING_READ_OWN: 'onboarding:read:own',
  ONBOARDING_WRITE_ANY: 'onboarding:write:any',
  ONBOARDING_WRITE_OWN: 'onboarding:write:own',
  ONBOARDING_QUEUE_READ: 'onboarding:queue:read',
  KYC_DOCUMENTS_WRITE_ANY: 'kyc-documents:write:any',
  KYC_DOCUMENTS_WRITE_OWN: 'kyc-documents:write:own',
  KYC_DOCUMENTS_REVIEW: 'kyc-documents:review',
  CATALOGUE_READ_ANY: 'catalogue:read:any',
  CATALOGUE_READ_OWN: 'catalogue:read:own',
  CATALOGUE_WRITE_ANY: 'catalogue:write:any',
  CATALOGUE_WRITE_OWN: 'catalogue:write:own',
  CATALOGUE_SUBMIT_OWN: 'catalogue:submit:own',
  CATALOGUE_QUEUE_READ: 'catalogue:queue:read',
  CATALOGUE_REVIEW: 'catalogue:review',
  WAREHOUSES_READ_ANY: 'warehouses:read:any',
  WAREHOUSES_READ_OWN: 'warehouses:read:own',
  WAREHOUSES_WRITE_ANY: 'warehouses:write:any',
  WAREHOUSES_WRITE_OWN: 'warehouses:write:own',
  INVENTORY_READ_ANY: 'inventory:read:any',
  INVENTORY_READ_OWN: 'inventory:read:own',
  INVENTORY_WRITE_ANY: 'inventory:write:any',
  INVENTORY_WRITE_OWN: 'inventory:write:own',
  INVENTORY_ADJUST_ANY: 'inventory:adjust:any',
  INVENTORY_ADJUST_OWN: 'inventory:adjust:own',
  OFFERS_READ_ANY: 'offers:read:any',
  OFFERS_READ_OWN: 'offers:read:own',
  OFFERS_WRITE_ANY: 'offers:write:any',
  OFFERS_WRITE_OWN: 'offers:write:own',
  OFFERS_SUBMIT_OWN: 'offers:submit:own',
  OFFERS_QUEUE_READ: 'offers:queue:read',
  OFFERS_REVIEW: 'offers:review',
  FARMER_PROFILE_READ_OWN: 'farmer-profile:read:own',
  FARMER_PROFILE_WRITE_OWN: 'farmer-profile:write:own',
  FARMER_ADDRESS_READ_OWN: 'farmer-addresses:read:own',
  FARMER_ADDRESS_WRITE_OWN: 'farmer-addresses:write:own',
  CART_READ_OWN: 'cart:read:own',
  CART_WRITE_OWN: 'cart:write:own',
  CHECKOUT_CREATE_OWN: 'checkout:create:own',
  CHECKOUT_READ_OWN: 'checkout:read:own',
  CHECKOUT_CANCEL_OWN: 'checkout:cancel:own',
  ORDERS_READ_OWN: 'orders:read:own',
  ORDERS_CANCEL_OWN: 'orders:cancel:own',
  FULFILMENT_ORDERS_READ_ANY: 'fulfilment-orders:read:any',
  FULFILMENT_ORDERS_READ_OWN: 'fulfilment-orders:read:own',
  FULFILMENT_ORDERS_MANAGE_ANY: 'fulfilment-orders:manage:any',
  FULFILMENT_ORDERS_MANAGE_OWN: 'fulfilment-orders:manage:own',
  DELIVERY_ASSIGNMENTS_READ_ANY: 'delivery-assignments:read:any',
  DELIVERY_ASSIGNMENTS_READ_OWN: 'delivery-assignments:read:own',
  DELIVERY_ASSIGNMENTS_MANAGE_ANY: 'delivery-assignments:manage:any',
  DELIVERY_ASSIGNMENTS_MANAGE_OWN: 'delivery-assignments:manage:own',
  PAYMENTS_CREATE_OWN: 'payments:create:own',
  PAYMENTS_CONFIRM_OWN: 'payments:confirm:own',
  PAYMENTS_READ_OWN: 'payments:read:own',
  FINANCE_COMMISSION_RULES_READ: 'finance-commission-rules:read',
  FINANCE_COMMISSION_RULES_WRITE: 'finance-commission-rules:write',
  FINANCE_LEDGER_READ: 'finance-ledger:read',
  FINANCE_COMMISSION_ENTRIES_READ: 'finance-commission-entries:read',
  FINANCE_COMMISSION_ENTRIES_MANAGE: 'finance-commission-entries:manage',
  FINANCE_SETTLEMENTS_READ: 'finance-settlements:read',
  FINANCE_SETTLEMENTS_MANAGE: 'finance-settlements:manage',
  PROMOTER_ATTRIBUTIONS_CREATE: 'promoter-attributions:create',
  PROMOTER_ATTRIBUTIONS_READ_ANY: 'promoter-attributions:read:any',
  PROMOTER_ATTRIBUTIONS_READ_OWN: 'promoter-attributions:read:own',
  PROMOTER_ATTRIBUTIONS_REVOKE: 'promoter-attributions:revoke',
  PAYOUT_ACCOUNTS_WRITE_OWN: 'payout-accounts:write:own',
  PAYOUT_ACCOUNTS_READ_OWN: 'payout-accounts:read:own',
  PAYOUT_ACCOUNTS_READ_ANY: 'payout-accounts:read:any',
  PAYOUT_ACCOUNTS_VERIFY: 'payout-accounts:verify',
  PAYOUT_STATEMENTS_READ_OWN: 'payout-statements:read:own',
  SUPPORT_TICKETS_CREATE_OWN: 'support-tickets:create:own',
  SUPPORT_TICKETS_READ_OWN: 'support-tickets:read:own',
  SUPPORT_TICKETS_READ_ANY: 'support-tickets:read:any',
  SUPPORT_TICKETS_MANAGE: 'support-tickets:manage',
  TALLY_SYNC_READ: 'tally-sync:read',
  TALLY_SYNC_MANAGE: 'tally-sync:manage',
  NOTIFICATIONS_READ_OWN: 'notifications:read:own',
  NOTIFICATIONS_READ_ANY: 'notifications:read:any',
  NOTIFICATIONS_MANAGE: 'notifications:manage',
  DASHBOARDS_READ: 'dashboards:read',
  DASHBOARDS_EXPORT: 'dashboards:export',
  ROLES_READ: 'roles:read',
  AUDIT_READ: 'audit:read',
} as const;

export type PermissionCode = (typeof PermissionCode)[keyof typeof PermissionCode];

export const permissionDefinitions: ReadonlyArray<{
  code: PermissionCode;
  description: string;
}> = [
  { code: PermissionCode.USERS_READ_ANY, description: 'Read any user account' },
  { code: PermissionCode.USERS_CREATE, description: 'Create user accounts' },
  { code: PermissionCode.USERS_UPDATE_ANY, description: 'Update any user account' },
  { code: PermissionCode.ORGANISATIONS_READ_ANY, description: 'Read any organisation' },
  { code: PermissionCode.ORGANISATIONS_READ_OWN, description: 'Read own organisation' },
  { code: PermissionCode.ORGANISATIONS_CREATE, description: 'Create organisations' },
  { code: PermissionCode.ORGANISATIONS_UPDATE_ANY, description: 'Update any organisation' },
  { code: PermissionCode.ORGANISATIONS_APPROVE, description: 'Approve or reject organisations' },
  { code: PermissionCode.MEMBERSHIPS_READ_ANY, description: 'Read any organisation membership' },
  { code: PermissionCode.MEMBERSHIPS_READ_OWN, description: 'Read own organisation memberships' },
  { code: PermissionCode.MEMBERSHIPS_CREATE, description: 'Create organisation memberships' },
  { code: PermissionCode.MEMBERSHIPS_UPDATE_ANY, description: 'Update organisation memberships' },
  { code: PermissionCode.ONBOARDING_READ_ANY, description: 'Read any onboarding profile' },
  { code: PermissionCode.ONBOARDING_READ_OWN, description: 'Read own onboarding profile' },
  { code: PermissionCode.ONBOARDING_WRITE_ANY, description: 'Write any onboarding profile' },
  { code: PermissionCode.ONBOARDING_WRITE_OWN, description: 'Write own onboarding profile' },
  { code: PermissionCode.ONBOARDING_QUEUE_READ, description: 'Read onboarding approval queues' },
  { code: PermissionCode.KYC_DOCUMENTS_WRITE_ANY, description: 'Write any KYC document metadata' },
  { code: PermissionCode.KYC_DOCUMENTS_WRITE_OWN, description: 'Write own KYC document metadata' },
  {
    code: PermissionCode.KYC_DOCUMENTS_REVIEW,
    description: 'Approve or reject KYC document metadata',
  },
  { code: PermissionCode.CATALOGUE_READ_ANY, description: 'Read any catalogue record' },
  { code: PermissionCode.CATALOGUE_READ_OWN, description: 'Read own company catalogue records' },
  { code: PermissionCode.CATALOGUE_WRITE_ANY, description: 'Write any catalogue record' },
  { code: PermissionCode.CATALOGUE_WRITE_OWN, description: 'Write own company catalogue records' },
  {
    code: PermissionCode.CATALOGUE_SUBMIT_OWN,
    description: 'Submit own catalogue records for review',
  },
  { code: PermissionCode.CATALOGUE_QUEUE_READ, description: 'Read catalogue review queues' },
  { code: PermissionCode.CATALOGUE_REVIEW, description: 'Approve or reject catalogue records' },
  { code: PermissionCode.WAREHOUSES_READ_ANY, description: 'Read any distributor warehouse' },
  { code: PermissionCode.WAREHOUSES_READ_OWN, description: 'Read own distributor warehouses' },
  { code: PermissionCode.WAREHOUSES_WRITE_ANY, description: 'Write any distributor warehouse' },
  { code: PermissionCode.WAREHOUSES_WRITE_OWN, description: 'Write own distributor warehouses' },
  { code: PermissionCode.INVENTORY_READ_ANY, description: 'Read any distributor inventory' },
  { code: PermissionCode.INVENTORY_READ_OWN, description: 'Read own distributor inventory' },
  { code: PermissionCode.INVENTORY_WRITE_ANY, description: 'Write any distributor batch metadata' },
  { code: PermissionCode.INVENTORY_WRITE_OWN, description: 'Write own distributor batch metadata' },
  { code: PermissionCode.INVENTORY_ADJUST_ANY, description: 'Adjust any distributor stock' },
  { code: PermissionCode.INVENTORY_ADJUST_OWN, description: 'Adjust own distributor stock' },
  { code: PermissionCode.OFFERS_READ_ANY, description: 'Read any distributor offer' },
  { code: PermissionCode.OFFERS_READ_OWN, description: 'Read own distributor offers' },
  { code: PermissionCode.OFFERS_WRITE_ANY, description: 'Write any distributor offer' },
  { code: PermissionCode.OFFERS_WRITE_OWN, description: 'Write own distributor offers' },
  {
    code: PermissionCode.OFFERS_SUBMIT_OWN,
    description: 'Submit own distributor offers for review',
  },
  { code: PermissionCode.OFFERS_QUEUE_READ, description: 'Read distributor offer review queues' },
  { code: PermissionCode.OFFERS_REVIEW, description: 'Approve or reject distributor offers' },
  { code: PermissionCode.FARMER_PROFILE_READ_OWN, description: 'Read own farmer profile' },
  { code: PermissionCode.FARMER_PROFILE_WRITE_OWN, description: 'Write own farmer profile' },
  { code: PermissionCode.FARMER_ADDRESS_READ_OWN, description: 'Read own farmer addresses' },
  { code: PermissionCode.FARMER_ADDRESS_WRITE_OWN, description: 'Write own farmer addresses' },
  { code: PermissionCode.CART_READ_OWN, description: 'Read own farmer cart' },
  { code: PermissionCode.CART_WRITE_OWN, description: 'Write own farmer cart' },
  {
    code: PermissionCode.CHECKOUT_CREATE_OWN,
    description: 'Create checkout from own farmer cart',
  },
  { code: PermissionCode.CHECKOUT_READ_OWN, description: 'Read own farmer checkouts' },
  {
    code: PermissionCode.CHECKOUT_CANCEL_OWN,
    description: 'Cancel eligible own unpaid or payment-failed farmer checkouts',
  },
  { code: PermissionCode.ORDERS_READ_OWN, description: 'Read own product orders' },
  {
    code: PermissionCode.ORDERS_CANCEL_OWN,
    description: 'Cancel eligible own unpaid or payment-failed product orders',
  },
  {
    code: PermissionCode.FULFILMENT_ORDERS_READ_ANY,
    description: 'Read any distributor fulfilment order',
  },
  {
    code: PermissionCode.FULFILMENT_ORDERS_READ_OWN,
    description: 'Read fulfilment orders for own distributor organisation',
  },
  {
    code: PermissionCode.FULFILMENT_ORDERS_MANAGE_ANY,
    description: 'Manage any distributor fulfilment order',
  },
  {
    code: PermissionCode.FULFILMENT_ORDERS_MANAGE_OWN,
    description: 'Manage fulfilment orders for own distributor organisation',
  },
  {
    code: PermissionCode.DELIVERY_ASSIGNMENTS_READ_ANY,
    description: 'Read any product delivery assignment',
  },
  {
    code: PermissionCode.DELIVERY_ASSIGNMENTS_READ_OWN,
    description: 'Read product delivery assignments assigned to self',
  },
  {
    code: PermissionCode.DELIVERY_ASSIGNMENTS_MANAGE_ANY,
    description: 'Assign and manage any product delivery assignment',
  },
  {
    code: PermissionCode.DELIVERY_ASSIGNMENTS_MANAGE_OWN,
    description: 'Manage product delivery assignments assigned to self',
  },
  { code: PermissionCode.PAYMENTS_CREATE_OWN, description: 'Create own mock payment intents' },
  { code: PermissionCode.PAYMENTS_CONFIRM_OWN, description: 'Confirm own mock payment intents' },
  { code: PermissionCode.PAYMENTS_READ_OWN, description: 'Read own mock payment intents' },
  { code: PermissionCode.FINANCE_COMMISSION_RULES_READ, description: 'Read commission rules' },
  {
    code: PermissionCode.FINANCE_COMMISSION_RULES_WRITE,
    description: 'Create new commission rule versions',
  },
  { code: PermissionCode.FINANCE_LEDGER_READ, description: 'Read financial ledger entries' },
  {
    code: PermissionCode.FINANCE_COMMISSION_ENTRIES_READ,
    description: 'Read commission entries',
  },
  {
    code: PermissionCode.FINANCE_COMMISSION_ENTRIES_MANAGE,
    description: 'Finalize or reverse commission entries',
  },
  { code: PermissionCode.FINANCE_SETTLEMENTS_READ, description: 'Read settlements' },
  { code: PermissionCode.FINANCE_SETTLEMENTS_MANAGE, description: 'Create settlements' },
  {
    code: PermissionCode.PROMOTER_ATTRIBUTIONS_CREATE,
    description: 'Attribute a promoter to a farmer',
  },
  {
    code: PermissionCode.PROMOTER_ATTRIBUTIONS_READ_ANY,
    description: 'Read any promoter attribution',
  },
  {
    code: PermissionCode.PROMOTER_ATTRIBUTIONS_READ_OWN,
    description: 'Read own promoter attributions',
  },
  {
    code: PermissionCode.PROMOTER_ATTRIBUTIONS_REVOKE,
    description: 'Revoke a promoter attribution',
  },
  { code: PermissionCode.PAYOUT_ACCOUNTS_WRITE_OWN, description: 'Write own payout account' },
  { code: PermissionCode.PAYOUT_ACCOUNTS_READ_OWN, description: 'Read own payout account' },
  { code: PermissionCode.PAYOUT_ACCOUNTS_READ_ANY, description: 'Read any payout account' },
  { code: PermissionCode.PAYOUT_ACCOUNTS_VERIFY, description: 'Verify or reject a payout account' },
  {
    code: PermissionCode.PAYOUT_STATEMENTS_READ_OWN,
    description: 'Read own payout statement',
  },
  { code: PermissionCode.SUPPORT_TICKETS_CREATE_OWN, description: 'Create own support tickets' },
  { code: PermissionCode.SUPPORT_TICKETS_READ_OWN, description: 'Read own support tickets' },
  { code: PermissionCode.SUPPORT_TICKETS_READ_ANY, description: 'Read any support ticket' },
  {
    code: PermissionCode.SUPPORT_TICKETS_MANAGE,
    description: 'Assign, escalate, resolve and close support tickets',
  },
  { code: PermissionCode.TALLY_SYNC_READ, description: 'Read Tally sync records and reconciliation' },
  {
    code: PermissionCode.TALLY_SYNC_MANAGE,
    description: 'Enqueue and attempt Tally sync records',
  },
  { code: PermissionCode.NOTIFICATIONS_READ_OWN, description: 'Read and mark read own notifications' },
  { code: PermissionCode.NOTIFICATIONS_READ_ANY, description: 'Read any notification' },
  {
    code: PermissionCode.NOTIFICATIONS_MANAGE,
    description: 'Enqueue and attempt delivery of notifications',
  },
  { code: PermissionCode.DASHBOARDS_READ, description: 'Read the operational dashboard summary' },
  {
    code: PermissionCode.DASHBOARDS_EXPORT,
    description: 'Export the operational dashboard summary',
  },
  { code: PermissionCode.ROLES_READ, description: 'Read platform roles and permission mappings' },
  { code: PermissionCode.AUDIT_READ, description: 'Read audit log entries' },
];

const allPermissionCodes = permissionDefinitions.map((permission) => permission.code);

export const rolePermissions: Readonly<Record<PlatformRole, ReadonlyArray<PermissionCode>>> = {
  [PlatformRole.SUPER_ADMIN]: allPermissionCodes,
  [PlatformRole.ADMIN]: allPermissionCodes,
  [PlatformRole.OPERATIONS_MANAGER]: [
    PermissionCode.USERS_READ_ANY,
    PermissionCode.ORGANISATIONS_READ_ANY,
    PermissionCode.ORGANISATIONS_UPDATE_ANY,
    PermissionCode.MEMBERSHIPS_READ_ANY,
    PermissionCode.MEMBERSHIPS_CREATE,
    PermissionCode.MEMBERSHIPS_UPDATE_ANY,
    PermissionCode.ONBOARDING_READ_ANY,
    PermissionCode.ONBOARDING_WRITE_ANY,
    PermissionCode.ONBOARDING_QUEUE_READ,
    PermissionCode.KYC_DOCUMENTS_WRITE_ANY,
    PermissionCode.KYC_DOCUMENTS_REVIEW,
    PermissionCode.CATALOGUE_READ_ANY,
    PermissionCode.CATALOGUE_QUEUE_READ,
    PermissionCode.WAREHOUSES_READ_ANY,
    PermissionCode.WAREHOUSES_WRITE_ANY,
    PermissionCode.INVENTORY_READ_ANY,
    PermissionCode.INVENTORY_WRITE_ANY,
    PermissionCode.INVENTORY_ADJUST_ANY,
    PermissionCode.FULFILMENT_ORDERS_READ_ANY,
    PermissionCode.FULFILMENT_ORDERS_MANAGE_ANY,
    PermissionCode.DELIVERY_ASSIGNMENTS_READ_ANY,
    PermissionCode.DELIVERY_ASSIGNMENTS_MANAGE_ANY,
    PermissionCode.OFFERS_READ_ANY,
    PermissionCode.OFFERS_WRITE_ANY,
    PermissionCode.OFFERS_QUEUE_READ,
    PermissionCode.OFFERS_REVIEW,
    PermissionCode.FINANCE_COMMISSION_RULES_READ,
    PermissionCode.FINANCE_LEDGER_READ,
    PermissionCode.FINANCE_COMMISSION_ENTRIES_READ,
    PermissionCode.FINANCE_SETTLEMENTS_READ,
    PermissionCode.PROMOTER_ATTRIBUTIONS_CREATE,
    PermissionCode.PROMOTER_ATTRIBUTIONS_READ_ANY,
    PermissionCode.PROMOTER_ATTRIBUTIONS_REVOKE,
    PermissionCode.PAYOUT_ACCOUNTS_READ_ANY,
    PermissionCode.PAYOUT_ACCOUNTS_VERIFY,
    PermissionCode.SUPPORT_TICKETS_CREATE_OWN,
    PermissionCode.SUPPORT_TICKETS_READ_OWN,
    PermissionCode.SUPPORT_TICKETS_READ_ANY,
    PermissionCode.SUPPORT_TICKETS_MANAGE,
    PermissionCode.TALLY_SYNC_READ,
    PermissionCode.NOTIFICATIONS_READ_OWN,
    PermissionCode.NOTIFICATIONS_READ_ANY,
    PermissionCode.NOTIFICATIONS_MANAGE,
    PermissionCode.DASHBOARDS_READ,
    PermissionCode.DASHBOARDS_EXPORT,
    PermissionCode.ROLES_READ,
    PermissionCode.AUDIT_READ,
  ],
  [PlatformRole.SUPPORT_AGENT]: [
    PermissionCode.USERS_READ_ANY,
    PermissionCode.ORGANISATIONS_READ_ANY,
    PermissionCode.MEMBERSHIPS_READ_ANY,
    PermissionCode.ONBOARDING_READ_ANY,
    PermissionCode.ONBOARDING_QUEUE_READ,
    PermissionCode.CATALOGUE_READ_ANY,
    PermissionCode.CATALOGUE_QUEUE_READ,
    PermissionCode.WAREHOUSES_READ_ANY,
    PermissionCode.INVENTORY_READ_ANY,
    PermissionCode.FULFILMENT_ORDERS_READ_ANY,
    PermissionCode.DELIVERY_ASSIGNMENTS_READ_ANY,
    PermissionCode.OFFERS_READ_ANY,
    PermissionCode.OFFERS_QUEUE_READ,
    PermissionCode.FINANCE_COMMISSION_RULES_READ,
    PermissionCode.FINANCE_LEDGER_READ,
    PermissionCode.FINANCE_COMMISSION_ENTRIES_READ,
    PermissionCode.FINANCE_SETTLEMENTS_READ,
    PermissionCode.SUPPORT_TICKETS_CREATE_OWN,
    PermissionCode.SUPPORT_TICKETS_READ_OWN,
    PermissionCode.SUPPORT_TICKETS_READ_ANY,
    PermissionCode.SUPPORT_TICKETS_MANAGE,
    PermissionCode.NOTIFICATIONS_READ_OWN,
    PermissionCode.NOTIFICATIONS_READ_ANY,
    PermissionCode.DASHBOARDS_READ,
    PermissionCode.DASHBOARDS_EXPORT,
    PermissionCode.ROLES_READ,
    PermissionCode.AUDIT_READ,
  ],
  [PlatformRole.FINANCE_MANAGER]: [
    PermissionCode.USERS_READ_ANY,
    PermissionCode.ORGANISATIONS_READ_ANY,
    PermissionCode.MEMBERSHIPS_READ_ANY,
    PermissionCode.ONBOARDING_READ_ANY,
    PermissionCode.ONBOARDING_QUEUE_READ,
    PermissionCode.CATALOGUE_READ_ANY,
    PermissionCode.CATALOGUE_QUEUE_READ,
    PermissionCode.WAREHOUSES_READ_ANY,
    PermissionCode.INVENTORY_READ_ANY,
    PermissionCode.FULFILMENT_ORDERS_READ_ANY,
    PermissionCode.DELIVERY_ASSIGNMENTS_READ_ANY,
    PermissionCode.OFFERS_READ_ANY,
    PermissionCode.FINANCE_COMMISSION_RULES_READ,
    PermissionCode.FINANCE_COMMISSION_RULES_WRITE,
    PermissionCode.FINANCE_LEDGER_READ,
    PermissionCode.FINANCE_COMMISSION_ENTRIES_READ,
    PermissionCode.FINANCE_COMMISSION_ENTRIES_MANAGE,
    PermissionCode.FINANCE_SETTLEMENTS_READ,
    PermissionCode.FINANCE_SETTLEMENTS_MANAGE,
    PermissionCode.PAYOUT_ACCOUNTS_READ_ANY,
    PermissionCode.PAYOUT_ACCOUNTS_VERIFY,
    PermissionCode.SUPPORT_TICKETS_CREATE_OWN,
    PermissionCode.SUPPORT_TICKETS_READ_OWN,
    PermissionCode.TALLY_SYNC_READ,
    PermissionCode.TALLY_SYNC_MANAGE,
    PermissionCode.NOTIFICATIONS_READ_OWN,
    PermissionCode.DASHBOARDS_READ,
    PermissionCode.DASHBOARDS_EXPORT,
    PermissionCode.ROLES_READ,
    PermissionCode.AUDIT_READ,
  ],
  [PlatformRole.CATALOGUE_REVIEWER]: [
    PermissionCode.ORGANISATIONS_READ_ANY,
    PermissionCode.MEMBERSHIPS_READ_ANY,
    PermissionCode.ONBOARDING_READ_ANY,
    PermissionCode.ONBOARDING_QUEUE_READ,
    PermissionCode.KYC_DOCUMENTS_REVIEW,
    PermissionCode.CATALOGUE_READ_ANY,
    PermissionCode.CATALOGUE_QUEUE_READ,
    PermissionCode.CATALOGUE_REVIEW,
    PermissionCode.OFFERS_READ_ANY,
    PermissionCode.OFFERS_QUEUE_READ,
    PermissionCode.OFFERS_REVIEW,
    PermissionCode.SUPPORT_TICKETS_CREATE_OWN,
    PermissionCode.SUPPORT_TICKETS_READ_OWN,
    PermissionCode.NOTIFICATIONS_READ_OWN,
    PermissionCode.DASHBOARDS_READ,
    PermissionCode.DASHBOARDS_EXPORT,
    PermissionCode.ROLES_READ,
    PermissionCode.AUDIT_READ,
  ],
  [PlatformRole.COMPANY_OWNER]: [
    PermissionCode.ORGANISATIONS_READ_OWN,
    PermissionCode.MEMBERSHIPS_READ_OWN,
    PermissionCode.ONBOARDING_READ_OWN,
    PermissionCode.ONBOARDING_WRITE_OWN,
    PermissionCode.KYC_DOCUMENTS_WRITE_OWN,
    PermissionCode.CATALOGUE_READ_OWN,
    PermissionCode.CATALOGUE_WRITE_OWN,
    PermissionCode.CATALOGUE_SUBMIT_OWN,
    PermissionCode.SUPPORT_TICKETS_CREATE_OWN,
    PermissionCode.SUPPORT_TICKETS_READ_OWN,
    PermissionCode.NOTIFICATIONS_READ_OWN,
    PermissionCode.DASHBOARDS_READ,
    PermissionCode.ROLES_READ,
  ],
  [PlatformRole.COMPANY_STAFF]: [
    PermissionCode.ORGANISATIONS_READ_OWN,
    PermissionCode.MEMBERSHIPS_READ_OWN,
    PermissionCode.ONBOARDING_READ_OWN,
    PermissionCode.ONBOARDING_WRITE_OWN,
    PermissionCode.KYC_DOCUMENTS_WRITE_OWN,
    PermissionCode.CATALOGUE_READ_OWN,
    PermissionCode.CATALOGUE_WRITE_OWN,
    PermissionCode.CATALOGUE_SUBMIT_OWN,
    PermissionCode.SUPPORT_TICKETS_CREATE_OWN,
    PermissionCode.SUPPORT_TICKETS_READ_OWN,
    PermissionCode.NOTIFICATIONS_READ_OWN,
    PermissionCode.DASHBOARDS_READ,
    PermissionCode.ROLES_READ,
  ],
  [PlatformRole.DISTRIBUTOR_OWNER]: [
    PermissionCode.ORGANISATIONS_READ_OWN,
    PermissionCode.MEMBERSHIPS_READ_OWN,
    PermissionCode.ONBOARDING_READ_OWN,
    PermissionCode.ONBOARDING_WRITE_OWN,
    PermissionCode.KYC_DOCUMENTS_WRITE_OWN,
    PermissionCode.WAREHOUSES_READ_OWN,
    PermissionCode.WAREHOUSES_WRITE_OWN,
    PermissionCode.INVENTORY_READ_OWN,
    PermissionCode.INVENTORY_WRITE_OWN,
    PermissionCode.INVENTORY_ADJUST_OWN,
    PermissionCode.OFFERS_READ_OWN,
    PermissionCode.OFFERS_WRITE_OWN,
    PermissionCode.OFFERS_SUBMIT_OWN,
    PermissionCode.FULFILMENT_ORDERS_READ_OWN,
    PermissionCode.FULFILMENT_ORDERS_MANAGE_OWN,
    PermissionCode.SUPPORT_TICKETS_CREATE_OWN,
    PermissionCode.SUPPORT_TICKETS_READ_OWN,
    PermissionCode.NOTIFICATIONS_READ_OWN,
    PermissionCode.DASHBOARDS_READ,
    PermissionCode.ROLES_READ,
  ],
  [PlatformRole.DISTRIBUTOR_STAFF]: [
    PermissionCode.ORGANISATIONS_READ_OWN,
    PermissionCode.MEMBERSHIPS_READ_OWN,
    PermissionCode.ONBOARDING_READ_OWN,
    PermissionCode.ONBOARDING_WRITE_OWN,
    PermissionCode.KYC_DOCUMENTS_WRITE_OWN,
    PermissionCode.WAREHOUSES_READ_OWN,
    PermissionCode.WAREHOUSES_WRITE_OWN,
    PermissionCode.INVENTORY_READ_OWN,
    PermissionCode.INVENTORY_WRITE_OWN,
    PermissionCode.INVENTORY_ADJUST_OWN,
    PermissionCode.OFFERS_READ_OWN,
    PermissionCode.OFFERS_WRITE_OWN,
    PermissionCode.OFFERS_SUBMIT_OWN,
    PermissionCode.FULFILMENT_ORDERS_READ_OWN,
    PermissionCode.FULFILMENT_ORDERS_MANAGE_OWN,
    PermissionCode.SUPPORT_TICKETS_CREATE_OWN,
    PermissionCode.SUPPORT_TICKETS_READ_OWN,
    PermissionCode.NOTIFICATIONS_READ_OWN,
    PermissionCode.DASHBOARDS_READ,
    PermissionCode.ROLES_READ,
  ],
  [PlatformRole.SERVICE_PROVIDER]: [
    PermissionCode.ORGANISATIONS_READ_OWN,
    PermissionCode.MEMBERSHIPS_READ_OWN,
    PermissionCode.ONBOARDING_READ_OWN,
    PermissionCode.ONBOARDING_WRITE_OWN,
    PermissionCode.KYC_DOCUMENTS_WRITE_OWN,
    PermissionCode.SUPPORT_TICKETS_CREATE_OWN,
    PermissionCode.SUPPORT_TICKETS_READ_OWN,
    PermissionCode.NOTIFICATIONS_READ_OWN,
    PermissionCode.DASHBOARDS_READ,
    PermissionCode.ROLES_READ,
  ],
  [PlatformRole.PROMOTER]: [
    PermissionCode.PROMOTER_ATTRIBUTIONS_READ_OWN,
    PermissionCode.PAYOUT_ACCOUNTS_WRITE_OWN,
    PermissionCode.PAYOUT_ACCOUNTS_READ_OWN,
    PermissionCode.PAYOUT_STATEMENTS_READ_OWN,
    PermissionCode.SUPPORT_TICKETS_CREATE_OWN,
    PermissionCode.SUPPORT_TICKETS_READ_OWN,
    PermissionCode.NOTIFICATIONS_READ_OWN,
    PermissionCode.DASHBOARDS_READ,
    PermissionCode.ROLES_READ,
  ],
  [PlatformRole.SALES_PARTNER]: [
    PermissionCode.PROMOTER_ATTRIBUTIONS_READ_OWN,
    PermissionCode.PAYOUT_ACCOUNTS_WRITE_OWN,
    PermissionCode.PAYOUT_ACCOUNTS_READ_OWN,
    PermissionCode.PAYOUT_STATEMENTS_READ_OWN,
    PermissionCode.SUPPORT_TICKETS_CREATE_OWN,
    PermissionCode.SUPPORT_TICKETS_READ_OWN,
    PermissionCode.NOTIFICATIONS_READ_OWN,
    PermissionCode.DASHBOARDS_READ,
    PermissionCode.ROLES_READ,
  ],
  [PlatformRole.DELIVERY_PARTNER]: [
    PermissionCode.DELIVERY_ASSIGNMENTS_READ_OWN,
    PermissionCode.DELIVERY_ASSIGNMENTS_MANAGE_OWN,
    PermissionCode.PAYOUT_ACCOUNTS_WRITE_OWN,
    PermissionCode.PAYOUT_ACCOUNTS_READ_OWN,
    PermissionCode.PAYOUT_STATEMENTS_READ_OWN,
    PermissionCode.SUPPORT_TICKETS_CREATE_OWN,
    PermissionCode.SUPPORT_TICKETS_READ_OWN,
    PermissionCode.NOTIFICATIONS_READ_OWN,
    PermissionCode.DASHBOARDS_READ,
    PermissionCode.ROLES_READ,
  ],
  [PlatformRole.FARMER]: [
    PermissionCode.FARMER_PROFILE_READ_OWN,
    PermissionCode.FARMER_PROFILE_WRITE_OWN,
    PermissionCode.FARMER_ADDRESS_READ_OWN,
    PermissionCode.FARMER_ADDRESS_WRITE_OWN,
    PermissionCode.CART_READ_OWN,
    PermissionCode.CART_WRITE_OWN,
    PermissionCode.CHECKOUT_CREATE_OWN,
    PermissionCode.CHECKOUT_READ_OWN,
    PermissionCode.CHECKOUT_CANCEL_OWN,
    PermissionCode.ORDERS_READ_OWN,
    PermissionCode.ORDERS_CANCEL_OWN,
    PermissionCode.PAYMENTS_CREATE_OWN,
    PermissionCode.PAYMENTS_CONFIRM_OWN,
    PermissionCode.PAYMENTS_READ_OWN,
    PermissionCode.SUPPORT_TICKETS_CREATE_OWN,
    PermissionCode.SUPPORT_TICKETS_READ_OWN,
    PermissionCode.NOTIFICATIONS_READ_OWN,
    PermissionCode.DASHBOARDS_READ,
  ],
};
